#ifndef DRAGONDROPTEST_CONFIG_H
#define DRAGONDROPTEST_CONFIG_H

#define DRAGONDROPTEST_VERSION_MAJOR ${DRAGONDROPTEST_VERSION_MAJOR}
#define DRAGONDROPTEST_VERSION_MINOR ${DRAGONDROPTEST_VERSION_MINOR}
#define DRAGONDROPTEST_VERSION_PATCH ${DRAGONDROPTEST_VERSION_PATCH}
#define DRAGONDROPTEST_VERSION_STRING "${DRAGONDROPTEST_VERSION_STRING}"

#endif